# Generated by Django 4.2.7 on 2026-02-24 06:20

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TaxSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('info_requested', 'Information Requested'), ('under_review', 'Under Consultant Review'), ('calculation_done', 'Calculation Done'), ('awaiting_confirmation', 'Awaiting Client Confirmation'), ('confirmed', 'Client Confirmed'), ('archived', 'Archived')], default='draft', max_length=30)),
                ('consultant_notes', models.TextField(blank=True, null=True)),
                ('info_request_message', models.TextField(blank=True, null=True)),
                ('total_assessable_income', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('total_qualifying_payments', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('personal_relief', models.DecimalField(decimal_places=2, default=Decimal('1800000.00'), max_digits=15)),
                ('rent_relief', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('net_taxable_income', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('gross_tax', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('total_tax_credits', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('net_tax_payable', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tax_submissions', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_submissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'tax_submissions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TaxYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(unique=True)),
                ('label', models.CharField(max_length=50)),
                ('assessment_year_start', models.DateField()),
                ('assessment_year_end', models.DateField()),
                ('personal_relief', models.DecimalField(decimal_places=2, default=Decimal('1800000.00'), max_digits=15)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'tax_years',
                'ordering': ['-year'],
            },
        ),
        migrations.CreateModel(
            name='TerminalBenefit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('benefit_types', models.CharField(blank=True, help_text='e.g., EPF, ETF, Pension, Gratuity', max_length=200, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('submission', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='terminal_benefit', to='tax_forms.taxsubmission')),
            ],
            options={
                'db_table': 'terminal_benefit',
            },
        ),
        migrations.AddField(
            model_name='taxsubmission',
            name='tax_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='submissions', to='tax_forms.taxyear'),
        ),
        migrations.CreateModel(
            name='TaxCredits',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apit_on_salary', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('wht_rent_interest_service', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('partnership_tax_credit', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('notes', models.TextField(blank=True, null=True)),
                ('submission', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tax_credits', to='tax_forms.taxsubmission')),
            ],
            options={
                'db_table': 'tax_credits',
            },
        ),
        migrations.CreateModel(
            name='SoleProprietorshipIncome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('business_name', models.CharField(blank=True, max_length=200, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('submission', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sole_proprietorship', to='tax_forms.taxsubmission')),
            ],
            options={
                'db_table': 'sole_proprietorship_income',
            },
        ),
        migrations.CreateModel(
            name='SharesStocks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200)),
                ('no_of_shares', models.IntegerField(default=0)),
                ('date_of_acquisition', models.DateField(blank=True, null=True)),
                ('cost_market_value', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('net_dividend_income', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('order', models.IntegerField(default=1)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shares_stocks', to='tax_forms.taxsubmission')),
            ],
            options={
                'db_table': 'shares_stocks',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='RentIncome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gross_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('wht_deducted', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('notes', models.TextField(blank=True, null=True)),
                ('submission', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rent_income', to='tax_forms.taxsubmission')),
            ],
            options={
                'db_table': 'rent_income',
            },
        ),
        migrations.CreateModel(
            name='QualifyingPayments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('donation_charitable', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('donation_government', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('solar_panels_expenditure', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('notes', models.TextField(blank=True, null=True)),
                ('submission', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='qualifying_payments', to='tax_forms.taxsubmission')),
            ],
            options={
                'db_table': 'qualifying_payments',
            },
        ),
        migrations.CreateModel(
            name='OtherIncome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('description', models.TextField(blank=True, null=True)),
                ('submission', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='other_income', to='tax_forms.taxsubmission')),
            ],
            options={
                'db_table': 'other_income',
            },
        ),
        migrations.CreateModel(
            name='OtherAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=300)),
                ('acquisition_type', models.CharField(choices=[('purchase', 'Purchase'), ('gift', 'Gift'), ('exchange', 'Exchange')], default='purchase', max_length=20)),
                ('date_of_acquisition', models.DateField(blank=True, null=True)),
                ('cost_value', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('order', models.IntegerField(default=1)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='other_assets', to='tax_forms.taxsubmission')),
            ],
            options={
                'db_table': 'other_assets',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='MotorVehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200)),
                ('registration_no', models.CharField(max_length=50)),
                ('date_of_acquisition', models.DateField(blank=True, null=True)),
                ('cost_market_value', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('order', models.IntegerField(default=1)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='motor_vehicles', to='tax_forms.taxsubmission')),
            ],
            options={
                'db_table': 'motor_vehicles',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='LocalEmploymentIncome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('employer_name', models.CharField(blank=True, max_length=200, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('submission', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='local_employment', to='tax_forms.taxsubmission')),
            ],
            options={
                'db_table': 'local_employment_income',
            },
        ),
        migrations.CreateModel(
            name='LoansGiven',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('borrower_name', models.CharField(max_length=200)),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('notes', models.TextField(blank=True, null=True)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loans_given', to='tax_forms.taxsubmission')),
            ],
            options={
                'db_table': 'loans_given',
            },
        ),
        migrations.CreateModel(
            name='Liability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=300)),
                ('security_on_liability', models.CharField(blank=True, max_length=300, null=True)),
                ('date_of_commencement', models.DateField(blank=True, null=True)),
                ('original_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('amount_as_at_date', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('amount_repaid_during_year', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('order', models.IntegerField(default=1)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liabilities', to='tax_forms.taxsubmission')),
            ],
            options={
                'db_table': 'liabilities',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='InterestIncome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('wht_deducted', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('notes', models.TextField(blank=True, null=True)),
                ('submission', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='interest_income', to='tax_forms.taxsubmission')),
            ],
            options={
                'db_table': 'interest_income',
            },
        ),
        migrations.CreateModel(
            name='ImmovableProperty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('situation_of_property', models.CharField(max_length=500)),
                ('date_of_acquisition', models.DateField(blank=True, null=True)),
                ('cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('market_value', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('order', models.IntegerField(default=1)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='immovable_properties', to='tax_forms.taxsubmission')),
            ],
            options={
                'db_table': 'immovable_properties',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='GoldSilverJewellery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, null=True)),
                ('value', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('submission', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='gold_jewellery', to='tax_forms.taxsubmission')),
            ],
            options={
                'db_table': 'gold_silver_jewellery',
            },
        ),
        migrations.CreateModel(
            name='ForeignIncome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employment_service_fee', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('other_foreign_income', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('notes', models.TextField(blank=True, null=True)),
                ('submission', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='foreign_income', to='tax_forms.taxsubmission')),
            ],
            options={
                'db_table': 'foreign_income',
            },
        ),
        migrations.CreateModel(
            name='DividendIncome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('notes', models.TextField(blank=True, null=True)),
                ('submission', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dividend_income', to='tax_forms.taxsubmission')),
            ],
            options={
                'db_table': 'dividend_income',
            },
        ),
        migrations.CreateModel(
            name='DisposalOfAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=300)),
                ('date_of_disposal', models.DateField(blank=True, null=True)),
                ('sales_proceed', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('date_acquired', models.DateField(blank=True, null=True)),
                ('cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('order', models.IntegerField(default=1)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disposals', to='tax_forms.taxsubmission')),
            ],
            options={
                'db_table': 'disposal_of_assets',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='DeclarantDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('telephone', models.CharField(blank=True, max_length=20, null=True)),
                ('mobile', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('nic_passport', models.CharField(max_length=50)),
                ('tin', models.CharField(blank=True, max_length=50, null=True)),
                ('pin', models.CharField(blank=True, max_length=50, null=True)),
                ('submission', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='declarant_details', to='tax_forms.taxsubmission')),
            ],
            options={
                'db_table': 'declarant_details',
            },
        ),
        migrations.CreateModel(
            name='CashInHand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('submission', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cash_in_hand', to='tax_forms.taxsubmission')),
            ],
            options={
                'db_table': 'cash_in_hand',
            },
        ),
        migrations.CreateModel(
            name='BusinessProperty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_business', models.CharField(max_length=200)),
                ('current_account_balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('capital_account_balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('order', models.IntegerField(default=1)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='business_properties', to='tax_forms.taxsubmission')),
            ],
            options={
                'db_table': 'business_properties',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='BankBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(max_length=200)),
                ('account_no', models.CharField(max_length=100)),
                ('amount_invested', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('interest', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('order', models.IntegerField(default=1)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_balances', to='tax_forms.taxsubmission')),
            ],
            options={
                'db_table': 'bank_balances',
                'ordering': ['order'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='taxsubmission',
            unique_together={('client', 'tax_year')},
        ),
        migrations.CreateModel(
            name='SelfAssessmentPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('installment_number', models.IntegerField(choices=[(1, '1st'), (2, '2nd'), (3, '3rd'), (4, '4th')])),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('payment_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='self_assessment_payments', to='tax_forms.taxsubmission')),
            ],
            options={
                'db_table': 'self_assessment_payments',
                'unique_together': {('submission', 'installment_number')},
            },
        ),
    ]
