# Generated by Django 4.2.7 on 2026-02-24 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tax_forms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankbalance',
            name='account_no',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='bankbalance',
            name='bank_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='businessproperty',
            name='name_of_business',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='disposalofasset',
            name='description',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='immovableproperty',
            name='situation_of_property',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='liability',
            name='description',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='loansgiven',
            name='borrower_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='motorvehicle',
            name='description',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='motorvehicle',
            name='registration_no',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='otherasset',
            name='description',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='sharesstocks',
            name='description',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
