# Generated by Django 4.2.7 on 2026-04-15 04:31

import apps.tax_forms.models
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tax_forms', '0003_submissioneditlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(default='TAX AUTOMATION PORTAL', max_length=200)),
                ('company_tagline', models.CharField(blank=True, default='PERSONAL INCOME TAX RETURN', max_length=300)),
                ('company_logo', models.ImageField(blank=True, null=True, upload_to=apps.tax_forms.models._logo_upload_path)),
                ('footer_text', models.CharField(blank=True, default='Tax Automation Portal | Confidential', max_length=300)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'System Settings',
                'verbose_name_plural': 'System Settings',
                'db_table': 'system_settings',
            },
        ),
        migrations.AddField(
            model_name='dividendincome',
            name='exempt_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Dividends from resident companies at 15% WHT — exempt from tax', max_digits=15),
        ),
        migrations.AddField(
            model_name='foreignincome',
            name='foreign_tax_paid',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Foreign tax already paid — eligible as tax credit', max_digits=15),
        ),
        migrations.AddField(
            model_name='foreignincome',
            name='source_country',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='foreignincome',
            name='treaty_rate',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Double-tax treaty rate (e.g. 0.15 for 15%). Leave blank for standard rate.', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='taxsubmission',
            name='exempt_dividend_income',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15),
        ),
        migrations.AddField(
            model_name='taxsubmission',
            name='ird_submission_file',
            field=models.FileField(blank=True, null=True, upload_to='ird_submissions/'),
        ),
        migrations.AddField(
            model_name='taxsubmission',
            name='ird_submitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='taxsubmission',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('overdue', 'Overdue')], default='pending', max_length=10),
        ),
        migrations.AddField(
            model_name='taxsubmission',
            name='payment_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='taxsubmission',
            name='payment_updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_updates', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='taxsubmission',
            name='slab_breakdown',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='WHTCertificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('rent', 'Rent'), ('interest', 'Interest'), ('service_fees', 'Service Fees'), ('employment', 'Employment (APIT)'), ('other', 'Other')], default='other', max_length=20)),
                ('certificate_file', models.FileField(blank=True, null=True, upload_to=apps.tax_forms.models._wht_cert_upload_path)),
                ('original_filename', models.CharField(blank=True, max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='WHT amount shown on certificate', max_digits=15)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wht_certificates', to='tax_forms.taxsubmission')),
            ],
            options={
                'db_table': 'wht_certificates',
                'ordering': ['category', '-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='PreviousYearAccessRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('denied', 'Denied')], default='pending', max_length=10)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_access_requests', to=settings.AUTH_USER_MODEL)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_requests', to=settings.AUTH_USER_MODEL)),
                ('tax_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_requests', to='tax_forms.taxyear')),
            ],
            options={
                'db_table': 'previous_year_access_requests',
                'ordering': ['-requested_at'],
                'unique_together': {('client', 'tax_year')},
            },
        ),
    ]
