# Generated by Django 4.2.7 on 2026-04-27 04:21

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tax_forms', '0008_seed_system_settings'),
    ]

    operations = [
        migrations.CreateModel(
            name='CashFlowStatement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opening_cash_in_hand', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('opening_favourable_banks', models.JSONField(blank=True, default=list)),
                ('opening_overdraft_banks', models.JSONField(blank=True, default=list)),
                ('receipt_employment_income', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('receipt_interest_fds', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('receipt_interest_savings', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('receipt_rent_income', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('receipt_tb_securities', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('receipt_sale_shares', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('receipt_dividend_income', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('receipt_drawings_sole_partner', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('receipt_bank_loan', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('receipt_other_loans', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('receipt_sale_land_building', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('receipt_sale_motor_vehicle', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('receipt_sale_other_assets', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('payment_purchase_land_building', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('payment_purchase_motor_vehicle', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('payment_purchase_other_assets', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('payment_repayment_bank_loan', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('payment_lease_rentals', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('payment_jewellery_gems', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('payment_other_loans', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('payment_wht', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('payment_income_tax', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('payment_apit', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('payment_investment_shares', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('payment_loans_given_others', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('closing_cash_in_hand', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('closing_favourable_banks', models.JSONField(blank=True, default=list)),
                ('closing_overdraft_banks', models.JSONField(blank=True, default=list)),
                ('living_expenses_year', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('submission', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cash_flow', to='tax_forms.taxsubmission')),
            ],
            options={
                'db_table': 'cash_flow_statements',
            },
        ),
    ]
