# Generated by Django 4.2.7 on 2026-04-15 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('client', 'Client'), ('consultant', 'Consultant'), ('handling_person', 'Handling Person'), ('admin', 'Admin'), ('accounts_division', 'Accounts Division')], default='client', max_length=20),
        ),
    ]
