# Generated by Django 4.2.7 on 2026-02-24 06:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tax_forms', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('t10_salary_slip', 'T10 / Salary Slips'), ('monthly_salary_slip', 'Monthly Salary Slips'), ('tax_direction_letter', 'Tax Direction Letter / Terminal Benefit Confirmation'), ('rent_agreement', 'Rent Agreement / WHT Deduction Certificates'), ('bank_balance_confirmation', 'Bank Balance Confirmation / WHT Certificates'), ('dividend_certificate', 'Dividend Certificate (Dividend Warrant)'), ('partnership_accounts', 'Receipt & Payment Details / Partnership Accounts'), ('other_income_proof', 'Other Income Proof Documents'), ('donation_proof', 'Donation Proof Document'), ('solar_invoice', 'Solar Panel Invoice & Grid Agreement'), ('self_assessment_receipt', 'Self Assessment Pay-in Slips / Online Receipt'), ('t10_certificate', 'T10 Certificate (APIT)'), ('wht_certificate', 'WHT Certificate'), ('bank_confirmation_letter', 'Bank / Financial Institute Confirmation Letter'), ('supporting_document', 'Supporting Document'), ('other', 'Other')], default='supporting_document', max_length=50)),
                ('section', models.CharField(choices=[('income', 'Income & Expenses'), ('qualifying_payments', 'Qualifying Payments'), ('tax_credits', 'Tax Credits'), ('assets', 'Assets'), ('liabilities', 'Liabilities'), ('declarant', 'Declarant Details'), ('general', 'General')], default='general', max_length=30)),
                ('file', models.FileField(upload_to='documents/%Y/%m/')),
                ('original_filename', models.CharField(max_length=255)),
                ('file_size', models.IntegerField(default=0)),
                ('description', models.CharField(blank=True, max_length=300, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='tax_forms.taxsubmission')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_documents', to=settings.AUTH_USER_MODEL)),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'documents',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
